Alisha.zariff
nadaalomranii/csc207-Project pull request #34
Opened 2024-11-25 17:31 UTC by nadaalomranii

2024-11-25 17:42 UTC, Sahirara requested changes
Overall looks really good. Some main issues were occuring:
- CommonAssignment entity: the class cannot have update grade (i.e. a setter) since it violates CA
- AddAssignmentCourseDataAccessInterface doesn't implement DataAccessInetrface: make sure it does
- At this current moment, not sure what conflict there is with AssignmentListView. Once you make the previous fixes try running this file using AppBuilder to see if there are any problems

2024-12-01 00:27 UTC, miralyousef approved these changes
Your code follows clean architecture and looks great!

Some steps moving forward:
- make sure you implement prepareFailView 
- make sure you have the appropriate documentation 

You're killing it!!

2024-12-01 00:27 UTC, miralyousef commented on src/main/java/interface_adapter/edit_assignment/EditAssignmentPresenter.java
> +        // note: this use case currently can't fail
what about when the new assignment name is the same as a dif assignment name? does that not need a failview?

2024-12-01 00:52 UTC, Sahirara approved these changes
Looks good! Great job :)

2024-12-01 00:53 UTC, merged